/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuctionBid {
  'placedAt' : Timestamp,
  'bidderId' : PlayerId,
  'amount' : Money,
}
export interface AuctionStateView {
  'startedAt' : Timestamp,
  'bids' : Array<AuctionBid>,
  'isOpen' : boolean,
  'spaceId' : SpaceId,
}
export type AvatarId = bigint;
export type BoardPosition = bigint;
export type ColorGroup = { 'red' : null } |
  { 'utility' : null } |
  { 'orange' : null } |
  { 'pink' : null } |
  { 'darkBlue' : null } |
  { 'green' : null } |
  { 'railroad' : null } |
  { 'brown' : null } |
  { 'lightBlue' : null } |
  { 'yellow' : null };
export interface DiceRoll { 'die1' : bigint, 'die2' : bigint }
export type GameError = { 'propertyNotOwned' : null } |
  { 'insufficientFunds' : null } |
  { 'alreadyMortgaged' : null } |
  { 'invalidPhase' : null } |
  { 'propertyAlreadyOwned' : null } |
  { 'tradeNotFound' : null } |
  { 'notTradeParticipant' : null } |
  { 'invalidBid' : null } |
  { 'alreadyBankrupt' : null } |
  { 'playerNotFound' : null } |
  { 'maxUpgradeReached' : null } |
  { 'gameNotFound' : null } |
  { 'notYourTurn' : null } |
  { 'notMortgaged' : null } |
  { 'notInJail' : null };
export type GameId = string;
export interface GameSessionView {
  'id' : GameId,
  'status' : GameStatus,
  'startedAt' : Timestamp,
  'currentPlayerIndex' : bigint,
  'updatedAt' : Timestamp,
  'players' : Array<PlayerStateView>,
  'turnPhase' : TurnPhaseView,
  'ownedProperties' : Array<OwnedPropertyView>,
  'lastDiceRoll' : [] | [DiceRoll],
  'lobbyCode' : LobbyCode,
  'pendingTrade' : [] | [TradeOfferView],
}
export type GameStatus = { 'active' : null } |
  { 'finished' : { 'winnerId' : PlayerId } };
export type JailStatus = {
    'inJail' : { 'hasGetOutCard' : boolean, 'turnsRemaining' : bigint }
  } |
  { 'notInJail' : null };
export type LobbyCode = string;
export type LobbyError = { 'lobbyNotFound' : null } |
  { 'lobbyAlreadyStarted' : null } |
  { 'notHost' : null } |
  { 'alreadyInLobby' : null } |
  { 'tooFewPlayers' : null } |
  { 'lobbyFull' : null } |
  { 'notInLobby' : null };
export interface LobbyPlayer {
  'id' : PlayerId,
  'username' : string,
  'joinedAt' : Timestamp,
  'isHost' : boolean,
  'isReady' : boolean,
  'avatarId' : AvatarId,
}
export type LobbyStatus = { 'starting' : null } |
  { 'finished' : null } |
  { 'waiting' : null } |
  { 'inProgress' : null };
export interface LobbyView {
  'status' : LobbyStatus,
  'code' : LobbyCode,
  'createdAt' : Timestamp,
  'gameId' : [] | [GameId],
  'players' : Array<LobbyPlayer>,
  'hostId' : PlayerId,
  'maxPlayers' : bigint,
}
export type Money = bigint;
export interface OwnedPropertyView {
  'upgradeLevel' : UpgradeLevel,
  'ownerId' : PlayerId,
  'deed' : PropertyDeed,
  'spaceId' : SpaceId,
  'isMortgaged' : boolean,
}
export type PlayerId = Principal;
export interface PlayerStateView {
  'id' : PlayerId,
  'isBankrupt' : boolean,
  'username' : string,
  'balance' : Money,
  'lastSeenAt' : Timestamp,
  'getOutOfJailCards' : bigint,
  'ownedSpaces' : Array<SpaceId>,
  'avatarId' : AvatarId,
  'jailStatus' : JailStatus,
  'position' : BoardPosition,
}
export interface PropertyDeed {
  'purchasePrice' : Money,
  'housePrice' : Money,
  'mortgageValue' : Money,
  'rentHouse1' : Money,
  'rentHouse2' : Money,
  'rentHouse3' : Money,
  'rentHouse4' : Money,
  'name' : string,
  'rentHotel' : Money,
  'spaceId' : SpaceId,
  'colorGroup' : ColorGroup,
  'rentBase' : Money,
}
export type SpaceId = bigint;
export type Timestamp = bigint;
export interface TradeOfferView {
  'id' : bigint,
  'status' : TradeStatus,
  'proposerSpaces' : Array<SpaceId>,
  'createdAt' : Timestamp,
  'proposerMoney' : Money,
  'recipientMoney' : Money,
  'recipientId' : PlayerId,
  'recipientSpaces' : Array<SpaceId>,
  'proposerId' : PlayerId,
}
export type TradeStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export type TurnPhaseView = { 'endTurn' : null } |
  { 'move' : null } |
  { 'roll' : null } |
  { 'landAndAct' : null } |
  { 'auction' : AuctionStateView };
export type UpgradeLevel = bigint;
export interface _SERVICE {
  'acceptTrade' : ActorMethod<
    [GameId, bigint],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'buyProperty' : ActorMethod<
    [GameId, SpaceId],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'createLobby' : ActorMethod<
    [string, AvatarId, bigint],
    { 'ok' : LobbyView } |
      { 'err' : LobbyError }
  >,
  'declineTrade' : ActorMethod<
    [GameId, bigint],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'endTurn' : ActorMethod<
    [GameId],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'getGame' : ActorMethod<[GameId], [] | [GameSessionView]>,
  'getLobby' : ActorMethod<[LobbyCode], [] | [LobbyView]>,
  'heartbeat' : ActorMethod<[GameId], undefined>,
  'joinLobby' : ActorMethod<
    [LobbyCode, string, AvatarId],
    { 'ok' : LobbyView } |
      { 'err' : LobbyError }
  >,
  'leaveLobby' : ActorMethod<
    [LobbyCode],
    { 'ok' : null } |
      { 'err' : LobbyError }
  >,
  'mortgageProperty' : ActorMethod<
    [GameId, SpaceId],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'passOnProperty' : ActorMethod<
    [GameId, SpaceId],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'payJailFine' : ActorMethod<
    [GameId],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'placeBid' : ActorMethod<
    [GameId, Money],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'proposeTrade' : ActorMethod<
    [GameId, PlayerId, Array<SpaceId>, Money, Array<SpaceId>, Money],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'reconnect' : ActorMethod<[], [] | [GameSessionView]>,
  'resolveAuction' : ActorMethod<
    [GameId],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'rollAndMove' : ActorMethod<
    [GameId],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'setReady' : ActorMethod<
    [LobbyCode, boolean],
    { 'ok' : LobbyView } |
      { 'err' : LobbyError }
  >,
  'startGame' : ActorMethod<
    [LobbyCode],
    { 'ok' : GameSessionView } |
      { 'err' : LobbyError }
  >,
  'unmortgageProperty' : ActorMethod<
    [GameId, SpaceId],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'upgradeProperty' : ActorMethod<
    [GameId, SpaceId],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
  'useGetOutOfJailCard' : ActorMethod<
    [GameId],
    { 'ok' : GameSessionView } |
      { 'err' : GameError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];