/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameId = IDL.Text;
export const PlayerId = IDL.Principal;
export const GameStatus = IDL.Variant({
  'active' : IDL.Null,
  'finished' : IDL.Record({ 'winnerId' : PlayerId }),
});
export const Timestamp = IDL.Int;
export const Money = IDL.Int;
export const SpaceId = IDL.Nat;
export const AvatarId = IDL.Nat;
export const JailStatus = IDL.Variant({
  'inJail' : IDL.Record({
    'hasGetOutCard' : IDL.Bool,
    'turnsRemaining' : IDL.Nat,
  }),
  'notInJail' : IDL.Null,
});
export const BoardPosition = IDL.Nat;
export const PlayerStateView = IDL.Record({
  'id' : PlayerId,
  'isBankrupt' : IDL.Bool,
  'username' : IDL.Text,
  'balance' : Money,
  'lastSeenAt' : Timestamp,
  'getOutOfJailCards' : IDL.Nat,
  'ownedSpaces' : IDL.Vec(SpaceId),
  'avatarId' : AvatarId,
  'jailStatus' : JailStatus,
  'position' : BoardPosition,
});
export const AuctionBid = IDL.Record({
  'placedAt' : Timestamp,
  'bidderId' : PlayerId,
  'amount' : Money,
});
export const AuctionStateView = IDL.Record({
  'startedAt' : Timestamp,
  'bids' : IDL.Vec(AuctionBid),
  'isOpen' : IDL.Bool,
  'spaceId' : SpaceId,
});
export const TurnPhaseView = IDL.Variant({
  'endTurn' : IDL.Null,
  'move' : IDL.Null,
  'roll' : IDL.Null,
  'landAndAct' : IDL.Null,
  'auction' : AuctionStateView,
});
export const UpgradeLevel = IDL.Nat;
export const ColorGroup = IDL.Variant({
  'red' : IDL.Null,
  'utility' : IDL.Null,
  'orange' : IDL.Null,
  'pink' : IDL.Null,
  'darkBlue' : IDL.Null,
  'green' : IDL.Null,
  'railroad' : IDL.Null,
  'brown' : IDL.Null,
  'lightBlue' : IDL.Null,
  'yellow' : IDL.Null,
});
export const PropertyDeed = IDL.Record({
  'purchasePrice' : Money,
  'housePrice' : Money,
  'mortgageValue' : Money,
  'rentHouse1' : Money,
  'rentHouse2' : Money,
  'rentHouse3' : Money,
  'rentHouse4' : Money,
  'name' : IDL.Text,
  'rentHotel' : Money,
  'spaceId' : SpaceId,
  'colorGroup' : ColorGroup,
  'rentBase' : Money,
});
export const OwnedPropertyView = IDL.Record({
  'upgradeLevel' : UpgradeLevel,
  'ownerId' : PlayerId,
  'deed' : PropertyDeed,
  'spaceId' : SpaceId,
  'isMortgaged' : IDL.Bool,
});
export const DiceRoll = IDL.Record({ 'die1' : IDL.Nat, 'die2' : IDL.Nat });
export const LobbyCode = IDL.Text;
export const TradeStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const TradeOfferView = IDL.Record({
  'id' : IDL.Nat,
  'status' : TradeStatus,
  'proposerSpaces' : IDL.Vec(SpaceId),
  'createdAt' : Timestamp,
  'proposerMoney' : Money,
  'recipientMoney' : Money,
  'recipientId' : PlayerId,
  'recipientSpaces' : IDL.Vec(SpaceId),
  'proposerId' : PlayerId,
});
export const GameSessionView = IDL.Record({
  'id' : GameId,
  'status' : GameStatus,
  'startedAt' : Timestamp,
  'currentPlayerIndex' : IDL.Nat,
  'updatedAt' : Timestamp,
  'players' : IDL.Vec(PlayerStateView),
  'turnPhase' : TurnPhaseView,
  'ownedProperties' : IDL.Vec(OwnedPropertyView),
  'lastDiceRoll' : IDL.Opt(DiceRoll),
  'lobbyCode' : LobbyCode,
  'pendingTrade' : IDL.Opt(TradeOfferView),
});
export const GameError = IDL.Variant({
  'propertyNotOwned' : IDL.Null,
  'insufficientFunds' : IDL.Null,
  'alreadyMortgaged' : IDL.Null,
  'invalidPhase' : IDL.Null,
  'propertyAlreadyOwned' : IDL.Null,
  'tradeNotFound' : IDL.Null,
  'notTradeParticipant' : IDL.Null,
  'invalidBid' : IDL.Null,
  'alreadyBankrupt' : IDL.Null,
  'playerNotFound' : IDL.Null,
  'maxUpgradeReached' : IDL.Null,
  'gameNotFound' : IDL.Null,
  'notYourTurn' : IDL.Null,
  'notMortgaged' : IDL.Null,
  'notInJail' : IDL.Null,
});
export const LobbyStatus = IDL.Variant({
  'starting' : IDL.Null,
  'finished' : IDL.Null,
  'waiting' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const LobbyPlayer = IDL.Record({
  'id' : PlayerId,
  'username' : IDL.Text,
  'joinedAt' : Timestamp,
  'isHost' : IDL.Bool,
  'isReady' : IDL.Bool,
  'avatarId' : AvatarId,
});
export const LobbyView = IDL.Record({
  'status' : LobbyStatus,
  'code' : LobbyCode,
  'createdAt' : Timestamp,
  'gameId' : IDL.Opt(GameId),
  'players' : IDL.Vec(LobbyPlayer),
  'hostId' : PlayerId,
  'maxPlayers' : IDL.Nat,
});
export const LobbyError = IDL.Variant({
  'lobbyNotFound' : IDL.Null,
  'lobbyAlreadyStarted' : IDL.Null,
  'notHost' : IDL.Null,
  'alreadyInLobby' : IDL.Null,
  'tooFewPlayers' : IDL.Null,
  'lobbyFull' : IDL.Null,
  'notInLobby' : IDL.Null,
});

export const idlService = IDL.Service({
  'acceptTrade' : IDL.Func(
      [GameId, IDL.Nat],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'buyProperty' : IDL.Func(
      [GameId, SpaceId],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'createLobby' : IDL.Func(
      [IDL.Text, AvatarId, IDL.Nat],
      [IDL.Variant({ 'ok' : LobbyView, 'err' : LobbyError })],
      [],
    ),
  'declineTrade' : IDL.Func(
      [GameId, IDL.Nat],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'endTurn' : IDL.Func(
      [GameId],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'getGame' : IDL.Func([GameId], [IDL.Opt(GameSessionView)], ['query']),
  'getLobby' : IDL.Func([LobbyCode], [IDL.Opt(LobbyView)], ['query']),
  'heartbeat' : IDL.Func([GameId], [], []),
  'joinLobby' : IDL.Func(
      [LobbyCode, IDL.Text, AvatarId],
      [IDL.Variant({ 'ok' : LobbyView, 'err' : LobbyError })],
      [],
    ),
  'leaveLobby' : IDL.Func(
      [LobbyCode],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : LobbyError })],
      [],
    ),
  'mortgageProperty' : IDL.Func(
      [GameId, SpaceId],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'passOnProperty' : IDL.Func(
      [GameId, SpaceId],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'payJailFine' : IDL.Func(
      [GameId],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'placeBid' : IDL.Func(
      [GameId, Money],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'proposeTrade' : IDL.Func(
      [GameId, PlayerId, IDL.Vec(SpaceId), Money, IDL.Vec(SpaceId), Money],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'reconnect' : IDL.Func([], [IDL.Opt(GameSessionView)], ['query']),
  'resolveAuction' : IDL.Func(
      [GameId],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'rollAndMove' : IDL.Func(
      [GameId],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'setReady' : IDL.Func(
      [LobbyCode, IDL.Bool],
      [IDL.Variant({ 'ok' : LobbyView, 'err' : LobbyError })],
      [],
    ),
  'startGame' : IDL.Func(
      [LobbyCode],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : LobbyError })],
      [],
    ),
  'unmortgageProperty' : IDL.Func(
      [GameId, SpaceId],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'upgradeProperty' : IDL.Func(
      [GameId, SpaceId],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
  'useGetOutOfJailCard' : IDL.Func(
      [GameId],
      [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameId = IDL.Text;
  const PlayerId = IDL.Principal;
  const GameStatus = IDL.Variant({
    'active' : IDL.Null,
    'finished' : IDL.Record({ 'winnerId' : PlayerId }),
  });
  const Timestamp = IDL.Int;
  const Money = IDL.Int;
  const SpaceId = IDL.Nat;
  const AvatarId = IDL.Nat;
  const JailStatus = IDL.Variant({
    'inJail' : IDL.Record({
      'hasGetOutCard' : IDL.Bool,
      'turnsRemaining' : IDL.Nat,
    }),
    'notInJail' : IDL.Null,
  });
  const BoardPosition = IDL.Nat;
  const PlayerStateView = IDL.Record({
    'id' : PlayerId,
    'isBankrupt' : IDL.Bool,
    'username' : IDL.Text,
    'balance' : Money,
    'lastSeenAt' : Timestamp,
    'getOutOfJailCards' : IDL.Nat,
    'ownedSpaces' : IDL.Vec(SpaceId),
    'avatarId' : AvatarId,
    'jailStatus' : JailStatus,
    'position' : BoardPosition,
  });
  const AuctionBid = IDL.Record({
    'placedAt' : Timestamp,
    'bidderId' : PlayerId,
    'amount' : Money,
  });
  const AuctionStateView = IDL.Record({
    'startedAt' : Timestamp,
    'bids' : IDL.Vec(AuctionBid),
    'isOpen' : IDL.Bool,
    'spaceId' : SpaceId,
  });
  const TurnPhaseView = IDL.Variant({
    'endTurn' : IDL.Null,
    'move' : IDL.Null,
    'roll' : IDL.Null,
    'landAndAct' : IDL.Null,
    'auction' : AuctionStateView,
  });
  const UpgradeLevel = IDL.Nat;
  const ColorGroup = IDL.Variant({
    'red' : IDL.Null,
    'utility' : IDL.Null,
    'orange' : IDL.Null,
    'pink' : IDL.Null,
    'darkBlue' : IDL.Null,
    'green' : IDL.Null,
    'railroad' : IDL.Null,
    'brown' : IDL.Null,
    'lightBlue' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const PropertyDeed = IDL.Record({
    'purchasePrice' : Money,
    'housePrice' : Money,
    'mortgageValue' : Money,
    'rentHouse1' : Money,
    'rentHouse2' : Money,
    'rentHouse3' : Money,
    'rentHouse4' : Money,
    'name' : IDL.Text,
    'rentHotel' : Money,
    'spaceId' : SpaceId,
    'colorGroup' : ColorGroup,
    'rentBase' : Money,
  });
  const OwnedPropertyView = IDL.Record({
    'upgradeLevel' : UpgradeLevel,
    'ownerId' : PlayerId,
    'deed' : PropertyDeed,
    'spaceId' : SpaceId,
    'isMortgaged' : IDL.Bool,
  });
  const DiceRoll = IDL.Record({ 'die1' : IDL.Nat, 'die2' : IDL.Nat });
  const LobbyCode = IDL.Text;
  const TradeStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const TradeOfferView = IDL.Record({
    'id' : IDL.Nat,
    'status' : TradeStatus,
    'proposerSpaces' : IDL.Vec(SpaceId),
    'createdAt' : Timestamp,
    'proposerMoney' : Money,
    'recipientMoney' : Money,
    'recipientId' : PlayerId,
    'recipientSpaces' : IDL.Vec(SpaceId),
    'proposerId' : PlayerId,
  });
  const GameSessionView = IDL.Record({
    'id' : GameId,
    'status' : GameStatus,
    'startedAt' : Timestamp,
    'currentPlayerIndex' : IDL.Nat,
    'updatedAt' : Timestamp,
    'players' : IDL.Vec(PlayerStateView),
    'turnPhase' : TurnPhaseView,
    'ownedProperties' : IDL.Vec(OwnedPropertyView),
    'lastDiceRoll' : IDL.Opt(DiceRoll),
    'lobbyCode' : LobbyCode,
    'pendingTrade' : IDL.Opt(TradeOfferView),
  });
  const GameError = IDL.Variant({
    'propertyNotOwned' : IDL.Null,
    'insufficientFunds' : IDL.Null,
    'alreadyMortgaged' : IDL.Null,
    'invalidPhase' : IDL.Null,
    'propertyAlreadyOwned' : IDL.Null,
    'tradeNotFound' : IDL.Null,
    'notTradeParticipant' : IDL.Null,
    'invalidBid' : IDL.Null,
    'alreadyBankrupt' : IDL.Null,
    'playerNotFound' : IDL.Null,
    'maxUpgradeReached' : IDL.Null,
    'gameNotFound' : IDL.Null,
    'notYourTurn' : IDL.Null,
    'notMortgaged' : IDL.Null,
    'notInJail' : IDL.Null,
  });
  const LobbyStatus = IDL.Variant({
    'starting' : IDL.Null,
    'finished' : IDL.Null,
    'waiting' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const LobbyPlayer = IDL.Record({
    'id' : PlayerId,
    'username' : IDL.Text,
    'joinedAt' : Timestamp,
    'isHost' : IDL.Bool,
    'isReady' : IDL.Bool,
    'avatarId' : AvatarId,
  });
  const LobbyView = IDL.Record({
    'status' : LobbyStatus,
    'code' : LobbyCode,
    'createdAt' : Timestamp,
    'gameId' : IDL.Opt(GameId),
    'players' : IDL.Vec(LobbyPlayer),
    'hostId' : PlayerId,
    'maxPlayers' : IDL.Nat,
  });
  const LobbyError = IDL.Variant({
    'lobbyNotFound' : IDL.Null,
    'lobbyAlreadyStarted' : IDL.Null,
    'notHost' : IDL.Null,
    'alreadyInLobby' : IDL.Null,
    'tooFewPlayers' : IDL.Null,
    'lobbyFull' : IDL.Null,
    'notInLobby' : IDL.Null,
  });
  
  return IDL.Service({
    'acceptTrade' : IDL.Func(
        [GameId, IDL.Nat],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'buyProperty' : IDL.Func(
        [GameId, SpaceId],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'createLobby' : IDL.Func(
        [IDL.Text, AvatarId, IDL.Nat],
        [IDL.Variant({ 'ok' : LobbyView, 'err' : LobbyError })],
        [],
      ),
    'declineTrade' : IDL.Func(
        [GameId, IDL.Nat],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'endTurn' : IDL.Func(
        [GameId],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'getGame' : IDL.Func([GameId], [IDL.Opt(GameSessionView)], ['query']),
    'getLobby' : IDL.Func([LobbyCode], [IDL.Opt(LobbyView)], ['query']),
    'heartbeat' : IDL.Func([GameId], [], []),
    'joinLobby' : IDL.Func(
        [LobbyCode, IDL.Text, AvatarId],
        [IDL.Variant({ 'ok' : LobbyView, 'err' : LobbyError })],
        [],
      ),
    'leaveLobby' : IDL.Func(
        [LobbyCode],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : LobbyError })],
        [],
      ),
    'mortgageProperty' : IDL.Func(
        [GameId, SpaceId],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'passOnProperty' : IDL.Func(
        [GameId, SpaceId],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'payJailFine' : IDL.Func(
        [GameId],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'placeBid' : IDL.Func(
        [GameId, Money],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'proposeTrade' : IDL.Func(
        [GameId, PlayerId, IDL.Vec(SpaceId), Money, IDL.Vec(SpaceId), Money],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'reconnect' : IDL.Func([], [IDL.Opt(GameSessionView)], ['query']),
    'resolveAuction' : IDL.Func(
        [GameId],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'rollAndMove' : IDL.Func(
        [GameId],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'setReady' : IDL.Func(
        [LobbyCode, IDL.Bool],
        [IDL.Variant({ 'ok' : LobbyView, 'err' : LobbyError })],
        [],
      ),
    'startGame' : IDL.Func(
        [LobbyCode],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : LobbyError })],
        [],
      ),
    'unmortgageProperty' : IDL.Func(
        [GameId, SpaceId],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'upgradeProperty' : IDL.Func(
        [GameId, SpaceId],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
    'useGetOutOfJailCard' : IDL.Func(
        [GameId],
        [IDL.Variant({ 'ok' : GameSessionView, 'err' : GameError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };