/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LobbyPlayer {
    id: PlayerId;
    username: string;
    joinedAt: Timestamp;
    isHost: boolean;
    isReady: boolean;
    avatarId: AvatarId;
}
export type Money = bigint;
export type Timestamp = bigint;
export interface PlayerStateView {
    id: PlayerId;
    isBankrupt: boolean;
    username: string;
    balance: Money;
    lastSeenAt: Timestamp;
    getOutOfJailCards: bigint;
    ownedSpaces: Array<SpaceId>;
    avatarId: AvatarId;
    jailStatus: JailStatus;
    position: BoardPosition;
}
export interface GameSessionView {
    id: GameId;
    status: GameStatus;
    startedAt: Timestamp;
    currentPlayerIndex: bigint;
    updatedAt: Timestamp;
    players: Array<PlayerStateView>;
    turnPhase: TurnPhaseView;
    ownedProperties: Array<OwnedPropertyView>;
    lastDiceRoll?: DiceRoll;
    lobbyCode: LobbyCode;
    pendingTrade?: TradeOfferView;
}
export type LobbyCode = string;
export type AvatarId = bigint;
export interface OwnedPropertyView {
    upgradeLevel: UpgradeLevel;
    ownerId: PlayerId;
    deed: PropertyDeed;
    spaceId: SpaceId;
    isMortgaged: boolean;
}
export type PlayerId = Principal;
export type TurnPhaseView = {
    __kind__: "endTurn";
    endTurn: null;
} | {
    __kind__: "move";
    move: null;
} | {
    __kind__: "roll";
    roll: null;
} | {
    __kind__: "landAndAct";
    landAndAct: null;
} | {
    __kind__: "auction";
    auction: AuctionStateView;
};
export interface LobbyView {
    status: LobbyStatus;
    code: LobbyCode;
    createdAt: Timestamp;
    gameId?: GameId;
    players: Array<LobbyPlayer>;
    hostId: PlayerId;
    maxPlayers: bigint;
}
export interface TradeOfferView {
    id: bigint;
    status: TradeStatus;
    proposerSpaces: Array<SpaceId>;
    createdAt: Timestamp;
    proposerMoney: Money;
    recipientMoney: Money;
    recipientId: PlayerId;
    recipientSpaces: Array<SpaceId>;
    proposerId: PlayerId;
}
export type SpaceId = bigint;
export type JailStatus = {
    __kind__: "inJail";
    inJail: {
        hasGetOutCard: boolean;
        turnsRemaining: bigint;
    };
} | {
    __kind__: "notInJail";
    notInJail: null;
};
export type UpgradeLevel = bigint;
export type GameStatus = {
    __kind__: "active";
    active: null;
} | {
    __kind__: "finished";
    finished: {
        winnerId: PlayerId;
    };
};
export type GameId = string;
export interface DiceRoll {
    die1: bigint;
    die2: bigint;
}
export type BoardPosition = bigint;
export interface AuctionStateView {
    startedAt: Timestamp;
    bids: Array<AuctionBid>;
    isOpen: boolean;
    spaceId: SpaceId;
}
export interface AuctionBid {
    placedAt: Timestamp;
    bidderId: PlayerId;
    amount: Money;
}
export interface PropertyDeed {
    purchasePrice: Money;
    housePrice: Money;
    mortgageValue: Money;
    rentHouse1: Money;
    rentHouse2: Money;
    rentHouse3: Money;
    rentHouse4: Money;
    name: string;
    rentHotel: Money;
    spaceId: SpaceId;
    colorGroup: ColorGroup;
    rentBase: Money;
}
export enum ColorGroup {
    red = "red",
    utility = "utility",
    orange = "orange",
    pink = "pink",
    darkBlue = "darkBlue",
    green = "green",
    railroad = "railroad",
    brown = "brown",
    lightBlue = "lightBlue",
    yellow = "yellow"
}
export enum GameError {
    propertyNotOwned = "propertyNotOwned",
    insufficientFunds = "insufficientFunds",
    alreadyMortgaged = "alreadyMortgaged",
    invalidPhase = "invalidPhase",
    propertyAlreadyOwned = "propertyAlreadyOwned",
    tradeNotFound = "tradeNotFound",
    notTradeParticipant = "notTradeParticipant",
    invalidBid = "invalidBid",
    alreadyBankrupt = "alreadyBankrupt",
    playerNotFound = "playerNotFound",
    maxUpgradeReached = "maxUpgradeReached",
    gameNotFound = "gameNotFound",
    notYourTurn = "notYourTurn",
    notMortgaged = "notMortgaged",
    notInJail = "notInJail"
}
export enum LobbyError {
    lobbyNotFound = "lobbyNotFound",
    lobbyAlreadyStarted = "lobbyAlreadyStarted",
    notHost = "notHost",
    alreadyInLobby = "alreadyInLobby",
    tooFewPlayers = "tooFewPlayers",
    lobbyFull = "lobbyFull",
    notInLobby = "notInLobby"
}
export enum LobbyStatus {
    starting = "starting",
    finished = "finished",
    waiting = "waiting",
    inProgress = "inProgress"
}
export enum TradeStatus {
    cancelled = "cancelled",
    pending = "pending",
    accepted = "accepted",
    declined = "declined"
}
export interface backendInterface {
    acceptTrade(gameId: GameId, tradeId: bigint): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    buyProperty(gameId: GameId, spaceId: SpaceId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    createLobby(username: string, avatarId: AvatarId, maxPlayers: bigint): Promise<{
        __kind__: "ok";
        ok: LobbyView;
    } | {
        __kind__: "err";
        err: LobbyError;
    }>;
    declineTrade(gameId: GameId, tradeId: bigint): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    endTurn(gameId: GameId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    getGame(gameId: GameId): Promise<GameSessionView | null>;
    getLobby(code: LobbyCode): Promise<LobbyView | null>;
    heartbeat(gameId: GameId): Promise<void>;
    joinLobby(code: LobbyCode, username: string, avatarId: AvatarId): Promise<{
        __kind__: "ok";
        ok: LobbyView;
    } | {
        __kind__: "err";
        err: LobbyError;
    }>;
    leaveLobby(code: LobbyCode): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: LobbyError;
    }>;
    mortgageProperty(gameId: GameId, spaceId: SpaceId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    passOnProperty(gameId: GameId, spaceId: SpaceId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    payJailFine(gameId: GameId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    placeBid(gameId: GameId, amount: Money): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    proposeTrade(gameId: GameId, recipientId: PlayerId, proposerSpaces: Array<SpaceId>, proposerMoney: Money, recipientSpaces: Array<SpaceId>, recipientMoney: Money): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    reconnect(): Promise<GameSessionView | null>;
    resolveAuction(gameId: GameId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    rollAndMove(gameId: GameId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    setReady(code: LobbyCode, ready: boolean): Promise<{
        __kind__: "ok";
        ok: LobbyView;
    } | {
        __kind__: "err";
        err: LobbyError;
    }>;
    startGame(code: LobbyCode): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: LobbyError;
    }>;
    unmortgageProperty(gameId: GameId, spaceId: SpaceId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    upgradeProperty(gameId: GameId, spaceId: SpaceId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
    useGetOutOfJailCard(gameId: GameId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }>;
}
import type { AuctionStateView as _AuctionStateView, AvatarId as _AvatarId, BoardPosition as _BoardPosition, ColorGroup as _ColorGroup, DiceRoll as _DiceRoll, GameError as _GameError, GameId as _GameId, GameSessionView as _GameSessionView, GameStatus as _GameStatus, JailStatus as _JailStatus, LobbyCode as _LobbyCode, LobbyError as _LobbyError, LobbyPlayer as _LobbyPlayer, LobbyStatus as _LobbyStatus, LobbyView as _LobbyView, Money as _Money, OwnedPropertyView as _OwnedPropertyView, PlayerId as _PlayerId, PlayerStateView as _PlayerStateView, PropertyDeed as _PropertyDeed, SpaceId as _SpaceId, Timestamp as _Timestamp, TradeOfferView as _TradeOfferView, TradeStatus as _TradeStatus, TurnPhaseView as _TurnPhaseView, UpgradeLevel as _UpgradeLevel } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptTrade(arg0: GameId, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptTrade(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptTrade(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async buyProperty(arg0: GameId, arg1: SpaceId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.buyProperty(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buyProperty(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createLobby(arg0: string, arg1: AvatarId, arg2: bigint): Promise<{
        __kind__: "ok";
        ok: LobbyView;
    } | {
        __kind__: "err";
        err: LobbyError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createLobby(arg0, arg1, arg2);
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLobby(arg0, arg1, arg2);
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async declineTrade(arg0: GameId, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.declineTrade(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineTrade(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async endTurn(arg0: GameId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.endTurn(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endTurn(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGame(arg0: GameId): Promise<GameSessionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGame(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGame(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLobby(arg0: LobbyCode): Promise<LobbyView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLobby(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLobby(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async heartbeat(arg0: GameId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.heartbeat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.heartbeat(arg0);
            return result;
        }
    }
    async joinLobby(arg0: LobbyCode, arg1: string, arg2: AvatarId): Promise<{
        __kind__: "ok";
        ok: LobbyView;
    } | {
        __kind__: "err";
        err: LobbyError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.joinLobby(arg0, arg1, arg2);
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinLobby(arg0, arg1, arg2);
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async leaveLobby(arg0: LobbyCode): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: LobbyError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveLobby(arg0);
                return from_candid_variant_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveLobby(arg0);
            return from_candid_variant_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async mortgageProperty(arg0: GameId, arg1: SpaceId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.mortgageProperty(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mortgageProperty(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async passOnProperty(arg0: GameId, arg1: SpaceId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.passOnProperty(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.passOnProperty(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async payJailFine(arg0: GameId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.payJailFine(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.payJailFine(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeBid(arg0: GameId, arg1: Money): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBid(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBid(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async proposeTrade(arg0: GameId, arg1: PlayerId, arg2: Array<SpaceId>, arg3: Money, arg4: Array<SpaceId>, arg5: Money): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.proposeTrade(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.proposeTrade(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async reconnect(): Promise<GameSessionView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.reconnect();
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reconnect();
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async resolveAuction(arg0: GameId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveAuction(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveAuction(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async rollAndMove(arg0: GameId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.rollAndMove(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rollAndMove(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async setReady(arg0: LobbyCode, arg1: boolean): Promise<{
        __kind__: "ok";
        ok: LobbyView;
    } | {
        __kind__: "err";
        err: LobbyError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setReady(arg0, arg1);
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setReady(arg0, arg1);
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async startGame(arg0: LobbyCode): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: LobbyError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.startGame(arg0);
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startGame(arg0);
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async unmortgageProperty(arg0: GameId, arg1: SpaceId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.unmortgageProperty(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unmortgageProperty(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async upgradeProperty(arg0: GameId, arg1: SpaceId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.upgradeProperty(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upgradeProperty(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async useGetOutOfJailCard(arg0: GameId): Promise<{
        __kind__: "ok";
        ok: GameSessionView;
    } | {
        __kind__: "err";
        err: GameError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.useGetOutOfJailCard(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.useGetOutOfJailCard(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ColorGroup_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColorGroup): ColorGroup {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_GameError_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameError): GameError {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_GameSessionView_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameSessionView): GameSessionView {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_GameStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameStatus): GameStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_JailStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JailStatus): JailStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_LobbyError_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LobbyError): LobbyError {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_LobbyStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LobbyStatus): LobbyStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_LobbyView_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LobbyView): LobbyView {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_OwnedPropertyView_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OwnedPropertyView): OwnedPropertyView {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerStateView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerStateView): PlayerStateView {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyDeed_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyDeed): PropertyDeed {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_TradeOfferView_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeOfferView): TradeOfferView {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_TradeStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeStatus): TradeStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_TurnPhaseView_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TurnPhaseView): TurnPhaseView {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DiceRoll]): DiceRoll | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TradeOfferView]): TradeOfferView | null {
    return value.length === 0 ? null : from_candid_TradeOfferView_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameId]): GameId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameSessionView]): GameSessionView | null {
    return value.length === 0 ? null : from_candid_GameSessionView_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LobbyView]): LobbyView | null {
    return value.length === 0 ? null : from_candid_LobbyView_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upgradeLevel: _UpgradeLevel;
    ownerId: _PlayerId;
    deed: _PropertyDeed;
    spaceId: _SpaceId;
    isMortgaged: boolean;
}): {
    upgradeLevel: UpgradeLevel;
    ownerId: PlayerId;
    deed: PropertyDeed;
    spaceId: SpaceId;
    isMortgaged: boolean;
} {
    return {
        upgradeLevel: value.upgradeLevel,
        ownerId: value.ownerId,
        deed: from_candid_PropertyDeed_n16(_uploadFile, _downloadFile, value.deed),
        spaceId: value.spaceId,
        isMortgaged: value.isMortgaged
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    purchasePrice: _Money;
    housePrice: _Money;
    mortgageValue: _Money;
    rentHouse1: _Money;
    rentHouse2: _Money;
    rentHouse3: _Money;
    rentHouse4: _Money;
    name: string;
    rentHotel: _Money;
    spaceId: _SpaceId;
    colorGroup: _ColorGroup;
    rentBase: _Money;
}): {
    purchasePrice: Money;
    housePrice: Money;
    mortgageValue: Money;
    rentHouse1: Money;
    rentHouse2: Money;
    rentHouse3: Money;
    rentHouse4: Money;
    name: string;
    rentHotel: Money;
    spaceId: SpaceId;
    colorGroup: ColorGroup;
    rentBase: Money;
} {
    return {
        purchasePrice: value.purchasePrice,
        housePrice: value.housePrice,
        mortgageValue: value.mortgageValue,
        rentHouse1: value.rentHouse1,
        rentHouse2: value.rentHouse2,
        rentHouse3: value.rentHouse3,
        rentHouse4: value.rentHouse4,
        name: value.name,
        rentHotel: value.rentHotel,
        spaceId: value.spaceId,
        colorGroup: from_candid_ColorGroup_n18(_uploadFile, _downloadFile, value.colorGroup),
        rentBase: value.rentBase
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TradeStatus;
    proposerSpaces: Array<_SpaceId>;
    createdAt: _Timestamp;
    proposerMoney: _Money;
    recipientMoney: _Money;
    recipientId: _PlayerId;
    recipientSpaces: Array<_SpaceId>;
    proposerId: _PlayerId;
}): {
    id: bigint;
    status: TradeStatus;
    proposerSpaces: Array<SpaceId>;
    createdAt: Timestamp;
    proposerMoney: Money;
    recipientMoney: Money;
    recipientId: PlayerId;
    recipientSpaces: Array<SpaceId>;
    proposerId: PlayerId;
} {
    return {
        id: value.id,
        status: from_candid_TradeStatus_n24(_uploadFile, _downloadFile, value.status),
        proposerSpaces: value.proposerSpaces,
        createdAt: value.createdAt,
        proposerMoney: value.proposerMoney,
        recipientMoney: value.recipientMoney,
        recipientId: value.recipientId,
        recipientSpaces: value.recipientSpaces,
        proposerId: value.proposerId
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GameId;
    status: _GameStatus;
    startedAt: _Timestamp;
    currentPlayerIndex: bigint;
    updatedAt: _Timestamp;
    players: Array<_PlayerStateView>;
    turnPhase: _TurnPhaseView;
    ownedProperties: Array<_OwnedPropertyView>;
    lastDiceRoll: [] | [_DiceRoll];
    lobbyCode: _LobbyCode;
    pendingTrade: [] | [_TradeOfferView];
}): {
    id: GameId;
    status: GameStatus;
    startedAt: Timestamp;
    currentPlayerIndex: bigint;
    updatedAt: Timestamp;
    players: Array<PlayerStateView>;
    turnPhase: TurnPhaseView;
    ownedProperties: Array<OwnedPropertyView>;
    lastDiceRoll?: DiceRoll;
    lobbyCode: LobbyCode;
    pendingTrade?: TradeOfferView;
} {
    return {
        id: value.id,
        status: from_candid_GameStatus_n4(_uploadFile, _downloadFile, value.status),
        startedAt: value.startedAt,
        currentPlayerIndex: value.currentPlayerIndex,
        updatedAt: value.updatedAt,
        players: from_candid_vec_n6(_uploadFile, _downloadFile, value.players),
        turnPhase: from_candid_TurnPhaseView_n11(_uploadFile, _downloadFile, value.turnPhase),
        ownedProperties: from_candid_vec_n13(_uploadFile, _downloadFile, value.ownedProperties),
        lastDiceRoll: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.lastDiceRoll)),
        lobbyCode: value.lobbyCode,
        pendingTrade: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.pendingTrade))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _LobbyStatus;
    code: _LobbyCode;
    createdAt: _Timestamp;
    gameId: [] | [_GameId];
    players: Array<_LobbyPlayer>;
    hostId: _PlayerId;
    maxPlayers: bigint;
}): {
    status: LobbyStatus;
    code: LobbyCode;
    createdAt: Timestamp;
    gameId?: GameId;
    players: Array<LobbyPlayer>;
    hostId: PlayerId;
    maxPlayers: bigint;
} {
    return {
        status: from_candid_LobbyStatus_n31(_uploadFile, _downloadFile, value.status),
        code: value.code,
        createdAt: value.createdAt,
        gameId: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.gameId)),
        players: value.players,
        hostId: value.hostId,
        maxPlayers: value.maxPlayers
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PlayerId;
    isBankrupt: boolean;
    username: string;
    balance: _Money;
    lastSeenAt: _Timestamp;
    getOutOfJailCards: bigint;
    ownedSpaces: Array<_SpaceId>;
    avatarId: _AvatarId;
    jailStatus: _JailStatus;
    position: _BoardPosition;
}): {
    id: PlayerId;
    isBankrupt: boolean;
    username: string;
    balance: Money;
    lastSeenAt: Timestamp;
    getOutOfJailCards: bigint;
    ownedSpaces: Array<SpaceId>;
    avatarId: AvatarId;
    jailStatus: JailStatus;
    position: BoardPosition;
} {
    return {
        id: value.id,
        isBankrupt: value.isBankrupt,
        username: value.username,
        balance: value.balance,
        lastSeenAt: value.lastSeenAt,
        getOutOfJailCards: value.getOutOfJailCards,
        ownedSpaces: value.ownedSpaces,
        avatarId: value.avatarId,
        jailStatus: from_candid_JailStatus_n9(_uploadFile, _downloadFile, value.jailStatus),
        position: value.position
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GameSessionView;
} | {
    err: _GameError;
}): {
    __kind__: "ok";
    ok: GameSessionView;
} | {
    __kind__: "err";
    err: GameError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GameSessionView_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_GameError_n26(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inJail: {
        hasGetOutCard: boolean;
        turnsRemaining: bigint;
    };
} | {
    notInJail: null;
}): {
    __kind__: "inJail";
    inJail: {
        hasGetOutCard: boolean;
        turnsRemaining: bigint;
    };
} | {
    __kind__: "notInJail";
    notInJail: null;
} {
    return "inJail" in value ? {
        __kind__: "inJail",
        inJail: value.inJail
    } : "notInJail" in value ? {
        __kind__: "notInJail",
        notInJail: value.notInJail
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endTurn: null;
} | {
    move: null;
} | {
    roll: null;
} | {
    landAndAct: null;
} | {
    auction: _AuctionStateView;
}): {
    __kind__: "endTurn";
    endTurn: null;
} | {
    __kind__: "move";
    move: null;
} | {
    __kind__: "roll";
    roll: null;
} | {
    __kind__: "landAndAct";
    landAndAct: null;
} | {
    __kind__: "auction";
    auction: AuctionStateView;
} {
    return "endTurn" in value ? {
        __kind__: "endTurn",
        endTurn: value.endTurn
    } : "move" in value ? {
        __kind__: "move",
        move: value.move
    } : "roll" in value ? {
        __kind__: "roll",
        roll: value.roll
    } : "landAndAct" in value ? {
        __kind__: "landAndAct",
        landAndAct: value.landAndAct
    } : "auction" in value ? {
        __kind__: "auction",
        auction: value.auction
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    utility: null;
} | {
    orange: null;
} | {
    pink: null;
} | {
    darkBlue: null;
} | {
    green: null;
} | {
    railroad: null;
} | {
    brown: null;
} | {
    lightBlue: null;
} | {
    yellow: null;
}): ColorGroup {
    return "red" in value ? ColorGroup.red : "utility" in value ? ColorGroup.utility : "orange" in value ? ColorGroup.orange : "pink" in value ? ColorGroup.pink : "darkBlue" in value ? ColorGroup.darkBlue : "green" in value ? ColorGroup.green : "railroad" in value ? ColorGroup.railroad : "brown" in value ? ColorGroup.brown : "lightBlue" in value ? ColorGroup.lightBlue : "yellow" in value ? ColorGroup.yellow : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    accepted: null;
} | {
    declined: null;
}): TradeStatus {
    return "cancelled" in value ? TradeStatus.cancelled : "pending" in value ? TradeStatus.pending : "accepted" in value ? TradeStatus.accepted : "declined" in value ? TradeStatus.declined : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    propertyNotOwned: null;
} | {
    insufficientFunds: null;
} | {
    alreadyMortgaged: null;
} | {
    invalidPhase: null;
} | {
    propertyAlreadyOwned: null;
} | {
    tradeNotFound: null;
} | {
    notTradeParticipant: null;
} | {
    invalidBid: null;
} | {
    alreadyBankrupt: null;
} | {
    playerNotFound: null;
} | {
    maxUpgradeReached: null;
} | {
    gameNotFound: null;
} | {
    notYourTurn: null;
} | {
    notMortgaged: null;
} | {
    notInJail: null;
}): GameError {
    return "propertyNotOwned" in value ? GameError.propertyNotOwned : "insufficientFunds" in value ? GameError.insufficientFunds : "alreadyMortgaged" in value ? GameError.alreadyMortgaged : "invalidPhase" in value ? GameError.invalidPhase : "propertyAlreadyOwned" in value ? GameError.propertyAlreadyOwned : "tradeNotFound" in value ? GameError.tradeNotFound : "notTradeParticipant" in value ? GameError.notTradeParticipant : "invalidBid" in value ? GameError.invalidBid : "alreadyBankrupt" in value ? GameError.alreadyBankrupt : "playerNotFound" in value ? GameError.playerNotFound : "maxUpgradeReached" in value ? GameError.maxUpgradeReached : "gameNotFound" in value ? GameError.gameNotFound : "notYourTurn" in value ? GameError.notYourTurn : "notMortgaged" in value ? GameError.notMortgaged : "notInJail" in value ? GameError.notInJail : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LobbyView;
} | {
    err: _LobbyError;
}): {
    __kind__: "ok";
    ok: LobbyView;
} | {
    __kind__: "err";
    err: LobbyError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_LobbyView_n29(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_LobbyError_n34(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    starting: null;
} | {
    finished: null;
} | {
    waiting: null;
} | {
    inProgress: null;
}): LobbyStatus {
    return "starting" in value ? LobbyStatus.starting : "finished" in value ? LobbyStatus.finished : "waiting" in value ? LobbyStatus.waiting : "inProgress" in value ? LobbyStatus.inProgress : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lobbyNotFound: null;
} | {
    lobbyAlreadyStarted: null;
} | {
    notHost: null;
} | {
    alreadyInLobby: null;
} | {
    tooFewPlayers: null;
} | {
    lobbyFull: null;
} | {
    notInLobby: null;
}): LobbyError {
    return "lobbyNotFound" in value ? LobbyError.lobbyNotFound : "lobbyAlreadyStarted" in value ? LobbyError.lobbyAlreadyStarted : "notHost" in value ? LobbyError.notHost : "alreadyInLobby" in value ? LobbyError.alreadyInLobby : "tooFewPlayers" in value ? LobbyError.tooFewPlayers : "lobbyFull" in value ? LobbyError.lobbyFull : "notInLobby" in value ? LobbyError.notInLobby : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _LobbyError;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: LobbyError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_LobbyError_n34(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GameSessionView;
} | {
    err: _LobbyError;
}): {
    __kind__: "ok";
    ok: GameSessionView;
} | {
    __kind__: "err";
    err: LobbyError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_GameSessionView_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_LobbyError_n34(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    finished: {
        winnerId: _PlayerId;
    };
}): {
    __kind__: "active";
    active: null;
} | {
    __kind__: "finished";
    finished: {
        winnerId: PlayerId;
    };
} {
    return "active" in value ? {
        __kind__: "active",
        active: value.active
    } : "finished" in value ? {
        __kind__: "finished",
        finished: value.finished
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OwnedPropertyView>): Array<OwnedPropertyView> {
    return value.map((x)=>from_candid_OwnedPropertyView_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlayerStateView>): Array<PlayerStateView> {
    return value.map((x)=>from_candid_PlayerStateView_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
